### ISSUE TITLE
Collapsible navigation

### ISSUE THREAD

**Issue by seancdavis** [contentlayerdev/website#18]
It's going to grow pretty quickly. It would be nice to be able to be collapsed by default, except for the current page, and to be able to expand it. Similar to how Stackbit's docs work.

**Comment by lukaswiesehan** [comment]
You can now add `collapsible` and `collapsed` properties to a Docs page's metadata like this:

```mdx
---
title: 'Source: Local Files'
excerpt: API reference for working with local files (Git CMS).
show_child_cards: true
last_edited: 2022-03-28
collapsible: true         <-- Makes the node collapsible (hide the nodes children). Defaults to false.
collapsed: true           <-- Initially collapses the node. Defaults to false.
---
```

If the currently viewed page is child of a collapsed node, it will automatically expand. A node will also expand when it's index page is viewed.
