### ISSUE TITLE
Investigate “inconsistent data” bug

### ISSUE THREAD

**Issue by schickling** [contentlayerdev/website#55]
![image](https://user-images.githubusercontent.com/1567498/168599798-0ca50aa9-d22d-41c9-9754-4e63f1935222.png)

**Comment by seancdavis** [comment]
This has been resolved.

<img width="446" alt="CleanShot 2023-05-17 at 13 09 04@2x" src="https://github.com/contentlayerdev/website/assets/5245089/a78a6ddf-3879-470c-b2df-67a4619a5e9a">
